name: mobile_app_frontend
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  cupertino_icons: ^1.0.5
  dio: ^5.2.1
  path_provider: ^2.0.11
  pinput: ^5.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo1.jpg
    - assets/images/landing.png
    - assets/images/tick.png